title: Are Ontologies Still Relevant in the Era of LLMs?
description: A Dagstuhl-style workshop co-located with [ISWC 2025](https://iswc2025.semanticweb.org/)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
