title: Are Ontologies Still Relevant in the Era of LLMs?
description: A Dagstuhl-style workshop co-located with ISWC 2025 <br> November 3, 2025
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
